-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Thu Feb 19 11:23:07 2026
-- Host        : DESKTOP-LF2M9VA running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_4bad_eth_buf_0_stub.vhdl
-- Design      : bd_4bad_eth_buf_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg484-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity bd_4bad_eth_buf_0 is
  Port ( 
    INTERRUPT : out STD_LOGIC;
    S_AXI_ACLK : in STD_LOGIC;
    S_AXI_ARESETN : in STD_LOGIC;
    S_AXI_AWADDR : in STD_LOGIC_VECTOR ( 17 downto 0 );
    S_AXI_AWVALID : in STD_LOGIC;
    S_AXI_AWREADY : out STD_LOGIC;
    S_AXI_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    S_AXI_WVALID : in STD_LOGIC;
    S_AXI_WREADY : out STD_LOGIC;
    S_AXI_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S_AXI_BVALID : out STD_LOGIC;
    S_AXI_BREADY : in STD_LOGIC;
    S_AXI_ARADDR : in STD_LOGIC_VECTOR ( 17 downto 0 );
    S_AXI_ARVALID : in STD_LOGIC;
    S_AXI_ARREADY : out STD_LOGIC;
    S_AXI_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S_AXI_RVALID : out STD_LOGIC;
    S_AXI_RREADY : in STD_LOGIC;
    EMAC_CLIENT_AUTONEG_INT : in STD_LOGIC;
    EMAC_RESET_DONE_INT : in STD_LOGIC;
    EMAC_RX_DCM_LOCKED_INT : in STD_LOGIC;
    PCSPMA_STATUS_VECTOR : in STD_LOGIC_VECTOR ( 15 downto 0 );
    AXI_STR_TXD_ACLK : in STD_LOGIC;
    AXI_STR_TXD_ARESETN : in STD_LOGIC;
    AXI_STR_TXD_TVALID : in STD_LOGIC;
    AXI_STR_TXD_TREADY : out STD_LOGIC;
    AXI_STR_TXD_TLAST : in STD_LOGIC;
    AXI_STR_TXD_TKEEP : in STD_LOGIC_VECTOR ( 3 downto 0 );
    AXI_STR_TXD_TDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    AXI_STR_TXC_ACLK : in STD_LOGIC;
    AXI_STR_TXC_ARESETN : in STD_LOGIC;
    AXI_STR_TXC_TVALID : in STD_LOGIC;
    AXI_STR_TXC_TREADY : out STD_LOGIC;
    AXI_STR_TXC_TLAST : in STD_LOGIC;
    AXI_STR_TXC_TKEEP : in STD_LOGIC_VECTOR ( 3 downto 0 );
    AXI_STR_TXC_TDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    AXI_STR_RXD_ACLK : in STD_LOGIC;
    AXI_STR_RXD_ARESETN : in STD_LOGIC;
    AXI_STR_RXD_VALID : out STD_LOGIC;
    AXI_STR_RXD_READY : in STD_LOGIC;
    AXI_STR_RXD_LAST : out STD_LOGIC;
    AXI_STR_RXD_KEEP : out STD_LOGIC_VECTOR ( 3 downto 0 );
    AXI_STR_RXD_DATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    AXI_STR_RXS_ACLK : in STD_LOGIC;
    AXI_STR_RXS_ARESETN : in STD_LOGIC;
    AXI_STR_RXS_VALID : out STD_LOGIC;
    AXI_STR_RXS_READY : in STD_LOGIC;
    AXI_STR_RXS_LAST : out STD_LOGIC;
    AXI_STR_RXS_KEEP : out STD_LOGIC_VECTOR ( 3 downto 0 );
    AXI_STR_RXS_DATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    pause_req : out STD_LOGIC;
    pause_val : out STD_LOGIC_VECTOR ( 16 to 31 );
    S_AXI_2TEMAC_AWADDR : out STD_LOGIC_VECTOR ( 11 downto 0 );
    S_AXI_2TEMAC_AWVALID : out STD_LOGIC;
    S_AXI_2TEMAC_AWREADY : in STD_LOGIC;
    S_AXI_2TEMAC_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_2TEMAC_WVALID : out STD_LOGIC;
    S_AXI_2TEMAC_WREADY : in STD_LOGIC;
    S_AXI_2TEMAC_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S_AXI_2TEMAC_BVALID : in STD_LOGIC;
    S_AXI_2TEMAC_BREADY : out STD_LOGIC;
    S_AXI_2TEMAC_ARADDR : out STD_LOGIC_VECTOR ( 11 downto 0 );
    S_AXI_2TEMAC_ARVALID : out STD_LOGIC;
    S_AXI_2TEMAC_ARREADY : in STD_LOGIC;
    S_AXI_2TEMAC_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_2TEMAC_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    S_AXI_2TEMAC_RVALID : in STD_LOGIC;
    S_AXI_2TEMAC_RREADY : out STD_LOGIC;
    RX_CLK_ENABLE_IN : in STD_LOGIC;
    rx_statistics_vector : in STD_LOGIC_VECTOR ( 27 downto 0 );
    rx_statistics_valid : in STD_LOGIC;
    rx_mac_aclk : in STD_LOGIC;
    rx_reset : in STD_LOGIC;
    rx_axis_mac_tdata : in STD_LOGIC_VECTOR ( 7 downto 0 );
    rx_axis_mac_tvalid : in STD_LOGIC;
    rx_axis_mac_tlast : in STD_LOGIC;
    rx_axis_mac_tuser : in STD_LOGIC;
    tx_ifg_delay : out STD_LOGIC_VECTOR ( 24 to 31 );
    tx_mac_aclk : in STD_LOGIC;
    tx_reset : in STD_LOGIC;
    tx_axis_mac_tdata : out STD_LOGIC_VECTOR ( 7 downto 0 );
    tx_axis_mac_tvalid : out STD_LOGIC;
    tx_axis_mac_tlast : out STD_LOGIC;
    tx_axis_mac_tuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    tx_axis_mac_tready : in STD_LOGIC;
    speed_is_10_100 : in STD_LOGIC;
    RESET2PCSPMA : out STD_LOGIC;
    RESET2TEMACn : out STD_LOGIC;
    PHY_RST_N : out STD_LOGIC;
    mdio_i_top : in STD_LOGIC;
    mdio_o_top : out STD_LOGIC;
    mdio_t_top : out STD_LOGIC;
    mdc_top : out STD_LOGIC;
    mdio_t_pcspma : in STD_LOGIC;
    mdio_o_pcspma : in STD_LOGIC;
    mdio_i_temac : out STD_LOGIC;
    mdio_o_temac : in STD_LOGIC;
    mdio_t_temac : in STD_LOGIC;
    mdc_temac : in STD_LOGIC;
    GTX_CLK : in STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of bd_4bad_eth_buf_0 : entity is "bd_4bad_eth_buf_0,axi_ethernet_buffer_v2_0_26,{}";
  attribute core_generation_info : string;
  attribute core_generation_info of bd_4bad_eth_buf_0 : entity is "bd_4bad_eth_buf_0,axi_ethernet_buffer_v2_0_26,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=axi_ethernet_buffer,x_ipVersion=2.0,x_ipCoreRevision=26,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_FAMILY=zynq,C_TXMEM=4096,C_TEMAC_ADDR_WIDTH=12,C_RXMEM=4096,C_TXCSUM=0,C_RXCSUM=0,C_PHYADDR=1,C_AVB=0,C_STATS=1,C_PHY_TYPE=3,C_SPEED_2P5=0,C_TYPE=1,C_TXVLAN_TRAN=0,C_RXVLAN_TRAN=0,C_TXVLAN_TAG=0,C_RXVLAN_TAG=0,C_TXVLAN_STRP=0,C_RXVLAN_STRP=0,C_MCAST_EXTEND=0,C_ENABLE_LVDS=0,C_ENABLE_1588=0,C_SIMULATION=0,C_PHY_RST_COUNT=500}";
  attribute downgradeipidentifiedwarnings : string;
  attribute downgradeipidentifiedwarnings of bd_4bad_eth_buf_0 : entity is "yes";
end bd_4bad_eth_buf_0;

architecture stub of bd_4bad_eth_buf_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "INTERRUPT,S_AXI_ACLK,S_AXI_ARESETN,S_AXI_AWADDR[17:0],S_AXI_AWVALID,S_AXI_AWREADY,S_AXI_WDATA[31:0],S_AXI_WSTRB[3:0],S_AXI_WVALID,S_AXI_WREADY,S_AXI_BRESP[1:0],S_AXI_BVALID,S_AXI_BREADY,S_AXI_ARADDR[17:0],S_AXI_ARVALID,S_AXI_ARREADY,S_AXI_RDATA[31:0],S_AXI_RRESP[1:0],S_AXI_RVALID,S_AXI_RREADY,EMAC_CLIENT_AUTONEG_INT,EMAC_RESET_DONE_INT,EMAC_RX_DCM_LOCKED_INT,PCSPMA_STATUS_VECTOR[15:0],AXI_STR_TXD_ACLK,AXI_STR_TXD_ARESETN,AXI_STR_TXD_TVALID,AXI_STR_TXD_TREADY,AXI_STR_TXD_TLAST,AXI_STR_TXD_TKEEP[3:0],AXI_STR_TXD_TDATA[31:0],AXI_STR_TXC_ACLK,AXI_STR_TXC_ARESETN,AXI_STR_TXC_TVALID,AXI_STR_TXC_TREADY,AXI_STR_TXC_TLAST,AXI_STR_TXC_TKEEP[3:0],AXI_STR_TXC_TDATA[31:0],AXI_STR_RXD_ACLK,AXI_STR_RXD_ARESETN,AXI_STR_RXD_VALID,AXI_STR_RXD_READY,AXI_STR_RXD_LAST,AXI_STR_RXD_KEEP[3:0],AXI_STR_RXD_DATA[31:0],AXI_STR_RXS_ACLK,AXI_STR_RXS_ARESETN,AXI_STR_RXS_VALID,AXI_STR_RXS_READY,AXI_STR_RXS_LAST,AXI_STR_RXS_KEEP[3:0],AXI_STR_RXS_DATA[31:0],pause_req,pause_val[16:31],S_AXI_2TEMAC_AWADDR[11:0],S_AXI_2TEMAC_AWVALID,S_AXI_2TEMAC_AWREADY,S_AXI_2TEMAC_WDATA[31:0],S_AXI_2TEMAC_WVALID,S_AXI_2TEMAC_WREADY,S_AXI_2TEMAC_BRESP[1:0],S_AXI_2TEMAC_BVALID,S_AXI_2TEMAC_BREADY,S_AXI_2TEMAC_ARADDR[11:0],S_AXI_2TEMAC_ARVALID,S_AXI_2TEMAC_ARREADY,S_AXI_2TEMAC_RDATA[31:0],S_AXI_2TEMAC_RRESP[1:0],S_AXI_2TEMAC_RVALID,S_AXI_2TEMAC_RREADY,RX_CLK_ENABLE_IN,rx_statistics_vector[27:0],rx_statistics_valid,rx_mac_aclk,rx_reset,rx_axis_mac_tdata[7:0],rx_axis_mac_tvalid,rx_axis_mac_tlast,rx_axis_mac_tuser,tx_ifg_delay[24:31],tx_mac_aclk,tx_reset,tx_axis_mac_tdata[7:0],tx_axis_mac_tvalid,tx_axis_mac_tlast,tx_axis_mac_tuser[0:0],tx_axis_mac_tready,speed_is_10_100,RESET2PCSPMA,RESET2TEMACn,PHY_RST_N,mdio_i_top,mdio_o_top,mdio_t_top,mdc_top,mdio_t_pcspma,mdio_o_pcspma,mdio_i_temac,mdio_o_temac,mdio_t_temac,mdc_temac,GTX_CLK";
  attribute x_interface_info : string;
  attribute x_interface_info of INTERRUPT : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute x_interface_mode : string;
  attribute x_interface_mode of INTERRUPT : signal is "master interrupt";
  attribute x_interface_parameter : string;
  attribute x_interface_parameter of INTERRUPT : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute x_interface_info of S_AXI_ACLK : signal is "xilinx.com:signal:clock:1.0 S_AXI_ACLK CLK";
  attribute x_interface_mode of S_AXI_ACLK : signal is "slave S_AXI_ACLK";
  attribute x_interface_parameter of S_AXI_ACLK : signal is "XIL_INTERFACENAME S_AXI_ACLK, ASSOCIATED_BUSIF S_AXI:S_AXI_2TEMAC, ASSOCIATED_RESET S_AXI_ARESETN, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute x_interface_info of S_AXI_ARESETN : signal is "xilinx.com:signal:reset:1.0 S_AXI_ARESETN RST";
  attribute x_interface_mode of S_AXI_ARESETN : signal is "slave S_AXI_ARESETN";
  attribute x_interface_parameter of S_AXI_ARESETN : signal is "XIL_INTERFACENAME S_AXI_ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of S_AXI_AWADDR : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWADDR";
  attribute x_interface_mode of S_AXI_AWADDR : signal is "slave S_AXI";
  attribute x_interface_parameter of S_AXI_AWADDR : signal is "XIL_INTERFACENAME S_AXI, FREQ_HZ 100000000, DATA_WIDTH 32, PROTOCOL AXI4LITE, ID_WIDTH 0, ADDR_WIDTH 18, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute x_interface_info of S_AXI_AWVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWVALID";
  attribute x_interface_info of S_AXI_AWREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI AWREADY";
  attribute x_interface_info of S_AXI_WDATA : signal is "xilinx.com:interface:aximm:1.0 S_AXI WDATA";
  attribute x_interface_info of S_AXI_WSTRB : signal is "xilinx.com:interface:aximm:1.0 S_AXI WSTRB";
  attribute x_interface_info of S_AXI_WVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI WVALID";
  attribute x_interface_info of S_AXI_WREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI WREADY";
  attribute x_interface_info of S_AXI_BRESP : signal is "xilinx.com:interface:aximm:1.0 S_AXI BRESP";
  attribute x_interface_info of S_AXI_BVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI BVALID";
  attribute x_interface_info of S_AXI_BREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI BREADY";
  attribute x_interface_info of S_AXI_ARADDR : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARADDR";
  attribute x_interface_info of S_AXI_ARVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARVALID";
  attribute x_interface_info of S_AXI_ARREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI ARREADY";
  attribute x_interface_info of S_AXI_RDATA : signal is "xilinx.com:interface:aximm:1.0 S_AXI RDATA";
  attribute x_interface_info of S_AXI_RRESP : signal is "xilinx.com:interface:aximm:1.0 S_AXI RRESP";
  attribute x_interface_info of S_AXI_RVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI RVALID";
  attribute x_interface_info of S_AXI_RREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI RREADY";
  attribute x_interface_info of EMAC_CLIENT_AUTONEG_INT : signal is "xilinx.com:signal:interrupt:1.0 EMAC_CLIENT_AUTONEG_INT INTERRUPT";
  attribute x_interface_mode of EMAC_CLIENT_AUTONEG_INT : signal is "slave EMAC_CLIENT_AUTONEG_INT";
  attribute x_interface_parameter of EMAC_CLIENT_AUTONEG_INT : signal is "XIL_INTERFACENAME EMAC_CLIENT_AUTONEG_INT, SENSITIVITY EDGE_RISING, PortWidth 1";
  attribute x_interface_info of AXI_STR_TXD_ACLK : signal is "xilinx.com:signal:clock:1.0 AXI_STR_TXD_ACLK CLK";
  attribute x_interface_mode of AXI_STR_TXD_ACLK : signal is "slave AXI_STR_TXD_ACLK";
  attribute x_interface_parameter of AXI_STR_TXD_ACLK : signal is "XIL_INTERFACENAME AXI_STR_TXD_ACLK, ASSOCIATED_BUSIF AXI_STR_TXD, ASSOCIATED_RESET AXI_STR_TXD_ARESETN, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_TXD_ARESETN : signal is "xilinx.com:signal:reset:1.0 AXI_STR_TXD_ARESETN RST";
  attribute x_interface_mode of AXI_STR_TXD_ARESETN : signal is "slave AXI_STR_TXD_ARESETN";
  attribute x_interface_parameter of AXI_STR_TXD_ARESETN : signal is "XIL_INTERFACENAME AXI_STR_TXD_ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_TXD_TVALID : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXD TVALID";
  attribute x_interface_mode of AXI_STR_TXD_TVALID : signal is "slave AXI_STR_TXD";
  attribute x_interface_parameter of AXI_STR_TXD_TVALID : signal is "XIL_INTERFACENAME AXI_STR_TXD, FREQ_HZ 100000000, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_TXD_TREADY : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXD TREADY";
  attribute x_interface_info of AXI_STR_TXD_TLAST : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXD TLAST";
  attribute x_interface_info of AXI_STR_TXD_TKEEP : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXD TKEEP";
  attribute x_interface_info of AXI_STR_TXD_TDATA : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXD TDATA";
  attribute x_interface_info of AXI_STR_TXC_ACLK : signal is "xilinx.com:signal:clock:1.0 AXI_STR_TXC_ACLK CLK";
  attribute x_interface_mode of AXI_STR_TXC_ACLK : signal is "slave AXI_STR_TXC_ACLK";
  attribute x_interface_parameter of AXI_STR_TXC_ACLK : signal is "XIL_INTERFACENAME AXI_STR_TXC_ACLK, ASSOCIATED_BUSIF AXI_STR_TXC, ASSOCIATED_RESET AXI_STR_TXC_ARESETN, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_TXC_ARESETN : signal is "xilinx.com:signal:reset:1.0 AXI_STR_TXC_ARESETN RST";
  attribute x_interface_mode of AXI_STR_TXC_ARESETN : signal is "slave AXI_STR_TXC_ARESETN";
  attribute x_interface_parameter of AXI_STR_TXC_ARESETN : signal is "XIL_INTERFACENAME AXI_STR_TXC_ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_TXC_TVALID : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXC TVALID";
  attribute x_interface_mode of AXI_STR_TXC_TVALID : signal is "slave AXI_STR_TXC";
  attribute x_interface_parameter of AXI_STR_TXC_TVALID : signal is "XIL_INTERFACENAME AXI_STR_TXC, FREQ_HZ 100000000, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_TXC_TREADY : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXC TREADY";
  attribute x_interface_info of AXI_STR_TXC_TLAST : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXC TLAST";
  attribute x_interface_info of AXI_STR_TXC_TKEEP : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXC TKEEP";
  attribute x_interface_info of AXI_STR_TXC_TDATA : signal is "xilinx.com:interface:axis:1.0 AXI_STR_TXC TDATA";
  attribute x_interface_info of AXI_STR_RXD_ACLK : signal is "xilinx.com:signal:clock:1.0 AXI_STR_RXD_ACLK CLK";
  attribute x_interface_mode of AXI_STR_RXD_ACLK : signal is "slave AXI_STR_RXD_ACLK";
  attribute x_interface_parameter of AXI_STR_RXD_ACLK : signal is "XIL_INTERFACENAME AXI_STR_RXD_ACLK, ASSOCIATED_BUSIF AXI_STR_RXD, ASSOCIATED_RESET AXI_STR_RXD_ARESETN, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_RXD_ARESETN : signal is "xilinx.com:signal:reset:1.0 AXI_STR_RXD_ARESETN RST";
  attribute x_interface_mode of AXI_STR_RXD_ARESETN : signal is "slave AXI_STR_RXD_ARESETN";
  attribute x_interface_parameter of AXI_STR_RXD_ARESETN : signal is "XIL_INTERFACENAME AXI_STR_RXD_ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_RXD_VALID : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXD TVALID";
  attribute x_interface_mode of AXI_STR_RXD_VALID : signal is "master AXI_STR_RXD";
  attribute x_interface_parameter of AXI_STR_RXD_VALID : signal is "XIL_INTERFACENAME AXI_STR_RXD, FREQ_HZ 100000000, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_RXD_READY : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXD TREADY";
  attribute x_interface_info of AXI_STR_RXD_LAST : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXD TLAST";
  attribute x_interface_info of AXI_STR_RXD_KEEP : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXD TKEEP";
  attribute x_interface_info of AXI_STR_RXD_DATA : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXD TDATA";
  attribute x_interface_info of AXI_STR_RXS_ACLK : signal is "xilinx.com:signal:clock:1.0 AXI_STR_RXS_ACLK CLK";
  attribute x_interface_mode of AXI_STR_RXS_ACLK : signal is "slave AXI_STR_RXS_ACLK";
  attribute x_interface_parameter of AXI_STR_RXS_ACLK : signal is "XIL_INTERFACENAME AXI_STR_RXS_ACLK, ASSOCIATED_BUSIF AXI_STR_RXS, ASSOCIATED_RESET AXI_STR_RXS_ARESETN, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_RXS_ARESETN : signal is "xilinx.com:signal:reset:1.0 AXI_STR_RXS_ARESETN RST";
  attribute x_interface_mode of AXI_STR_RXS_ARESETN : signal is "slave AXI_STR_RXS_ARESETN";
  attribute x_interface_parameter of AXI_STR_RXS_ARESETN : signal is "XIL_INTERFACENAME AXI_STR_RXS_ARESETN, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_RXS_VALID : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXS TVALID";
  attribute x_interface_mode of AXI_STR_RXS_VALID : signal is "master AXI_STR_RXS";
  attribute x_interface_parameter of AXI_STR_RXS_VALID : signal is "XIL_INTERFACENAME AXI_STR_RXS, FREQ_HZ 100000000, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 1, HAS_TLAST 1, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute x_interface_info of AXI_STR_RXS_READY : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXS TREADY";
  attribute x_interface_info of AXI_STR_RXS_LAST : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXS TLAST";
  attribute x_interface_info of AXI_STR_RXS_KEEP : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXS TKEEP";
  attribute x_interface_info of AXI_STR_RXS_DATA : signal is "xilinx.com:interface:axis:1.0 AXI_STR_RXS TDATA";
  attribute x_interface_info of S_AXI_2TEMAC_AWADDR : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC AWADDR";
  attribute x_interface_mode of S_AXI_2TEMAC_AWADDR : signal is "master S_AXI_2TEMAC";
  attribute x_interface_parameter of S_AXI_2TEMAC_AWADDR : signal is "XIL_INTERFACENAME S_AXI_2TEMAC, FREQ_HZ 100000000, DATA_WIDTH 32, PROTOCOL AXI4LITE, ID_WIDTH 0, ADDR_WIDTH 12, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute x_interface_info of S_AXI_2TEMAC_AWVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC AWVALID";
  attribute x_interface_info of S_AXI_2TEMAC_AWREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC AWREADY";
  attribute x_interface_info of S_AXI_2TEMAC_WDATA : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC WDATA";
  attribute x_interface_info of S_AXI_2TEMAC_WVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC WVALID";
  attribute x_interface_info of S_AXI_2TEMAC_WREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC WREADY";
  attribute x_interface_info of S_AXI_2TEMAC_BRESP : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC BRESP";
  attribute x_interface_info of S_AXI_2TEMAC_BVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC BVALID";
  attribute x_interface_info of S_AXI_2TEMAC_BREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC BREADY";
  attribute x_interface_info of S_AXI_2TEMAC_ARADDR : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC ARADDR";
  attribute x_interface_info of S_AXI_2TEMAC_ARVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC ARVALID";
  attribute x_interface_info of S_AXI_2TEMAC_ARREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC ARREADY";
  attribute x_interface_info of S_AXI_2TEMAC_RDATA : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC RDATA";
  attribute x_interface_info of S_AXI_2TEMAC_RRESP : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC RRESP";
  attribute x_interface_info of S_AXI_2TEMAC_RVALID : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC RVALID";
  attribute x_interface_info of S_AXI_2TEMAC_RREADY : signal is "xilinx.com:interface:aximm:1.0 S_AXI_2TEMAC RREADY";
  attribute x_interface_info of RX_CLK_ENABLE_IN : signal is "xilinx.com:signal:clockenable:1.0 RX_CLK_ENABLE_IN CE";
  attribute x_interface_mode of RX_CLK_ENABLE_IN : signal is "slave RX_CLK_ENABLE_IN";
  attribute x_interface_parameter of RX_CLK_ENABLE_IN : signal is "XIL_INTERFACENAME RX_CLK_ENABLE_IN, POLARITY ACTIVE_LOW";
  attribute x_interface_info of rx_mac_aclk : signal is "xilinx.com:signal:clock:1.0 rx_mac_aclk CLK";
  attribute x_interface_mode of rx_mac_aclk : signal is "slave rx_mac_aclk";
  attribute x_interface_parameter of rx_mac_aclk : signal is "XIL_INTERFACENAME rx_mac_aclk, ASSOCIATED_BUSIF RX_AXIS_MAC, FREQ_HZ 125000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN /mac/rx_mac_aclk, INSERT_VIP 0";
  attribute x_interface_info of rx_reset : signal is "xilinx.com:signal:reset:1.0 rx_reset RST";
  attribute x_interface_mode of rx_reset : signal is "slave rx_reset";
  attribute x_interface_parameter of rx_reset : signal is "XIL_INTERFACENAME rx_reset, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute x_interface_info of rx_axis_mac_tdata : signal is "xilinx.com:interface:axis:1.0 RX_AXIS_MAC TDATA";
  attribute x_interface_mode of rx_axis_mac_tdata : signal is "slave RX_AXIS_MAC";
  attribute x_interface_parameter of rx_axis_mac_tdata : signal is "XIL_INTERFACENAME RX_AXIS_MAC, FREQ_HZ 125000000, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 1, HAS_TREADY 0, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 1, PHASE 0.0, CLK_DOMAIN /mac/rx_mac_aclk, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute x_interface_info of rx_axis_mac_tvalid : signal is "xilinx.com:interface:axis:1.0 RX_AXIS_MAC TVALID";
  attribute x_interface_info of rx_axis_mac_tlast : signal is "xilinx.com:interface:axis:1.0 RX_AXIS_MAC TLAST";
  attribute x_interface_info of rx_axis_mac_tuser : signal is "xilinx.com:interface:axis:1.0 RX_AXIS_MAC TUSER";
  attribute x_interface_info of tx_mac_aclk : signal is "xilinx.com:signal:clock:1.0 tx_mac_aclk CLK";
  attribute x_interface_mode of tx_mac_aclk : signal is "slave tx_mac_aclk";
  attribute x_interface_parameter of tx_mac_aclk : signal is "XIL_INTERFACENAME tx_mac_aclk, ASSOCIATED_BUSIF TX_AXIS_MAC, FREQ_HZ 125000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK1, INSERT_VIP 0";
  attribute x_interface_info of tx_reset : signal is "xilinx.com:signal:reset:1.0 tx_reset RST";
  attribute x_interface_mode of tx_reset : signal is "slave tx_reset";
  attribute x_interface_parameter of tx_reset : signal is "XIL_INTERFACENAME tx_reset, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute x_interface_info of tx_axis_mac_tdata : signal is "xilinx.com:interface:axis:1.0 TX_AXIS_MAC TDATA";
  attribute x_interface_mode of tx_axis_mac_tdata : signal is "master TX_AXIS_MAC";
  attribute x_interface_parameter of tx_axis_mac_tdata : signal is "XIL_INTERFACENAME TX_AXIS_MAC, FREQ_HZ 125000000, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 1, PHASE 0.0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK1, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute x_interface_info of tx_axis_mac_tvalid : signal is "xilinx.com:interface:axis:1.0 TX_AXIS_MAC TVALID";
  attribute x_interface_info of tx_axis_mac_tlast : signal is "xilinx.com:interface:axis:1.0 TX_AXIS_MAC TLAST";
  attribute x_interface_info of tx_axis_mac_tuser : signal is "xilinx.com:interface:axis:1.0 TX_AXIS_MAC TUSER";
  attribute x_interface_info of tx_axis_mac_tready : signal is "xilinx.com:interface:axis:1.0 TX_AXIS_MAC TREADY";
  attribute x_interface_info of RESET2PCSPMA : signal is "xilinx.com:signal:reset:1.0 RESET2PCSPMA RST";
  attribute x_interface_mode of RESET2PCSPMA : signal is "master RESET2PCSPMA";
  attribute x_interface_parameter of RESET2PCSPMA : signal is "XIL_INTERFACENAME RESET2PCSPMA, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute x_interface_info of RESET2TEMACn : signal is "xilinx.com:signal:reset:1.0 RESET2TEMACn RST";
  attribute x_interface_mode of RESET2TEMACn : signal is "master RESET2TEMACn";
  attribute x_interface_parameter of RESET2TEMACn : signal is "XIL_INTERFACENAME RESET2TEMACn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of PHY_RST_N : signal is "xilinx.com:signal:reset:1.0 PHY_RST_N RST";
  attribute x_interface_mode of PHY_RST_N : signal is "master PHY_RST_N";
  attribute x_interface_parameter of PHY_RST_N : signal is "XIL_INTERFACENAME PHY_RST_N, BOARD.ASSOCIATED_PARAM PHYRST_BOARD_INTERFACE, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute x_interface_info of mdio_i_top : signal is "xilinx.com:interface:mdio:1.0 mdio_to_top MDIO_I";
  attribute x_interface_mode of mdio_i_top : signal is "master mdio_to_top";
  attribute x_interface_parameter of mdio_i_top : signal is "XIL_INTERFACENAME mdio_to_top, BOARD.ASSOCIATED_PARAM MDIO_BOARD_INTERFACE, CAN_DEBUG false";
  attribute x_interface_info of mdio_o_top : signal is "xilinx.com:interface:mdio:1.0 mdio_to_top MDIO_O";
  attribute x_interface_info of mdio_t_top : signal is "xilinx.com:interface:mdio:1.0 mdio_to_top MDIO_T";
  attribute x_interface_info of mdc_top : signal is "xilinx.com:interface:mdio:1.0 mdio_to_top MDC";
  attribute x_interface_info of mdio_i_temac : signal is "xilinx.com:interface:mdio:1.0 mdio_temac MDIO_I";
  attribute x_interface_mode of mdio_i_temac : signal is "mirroredMaster mdio_temac";
  attribute x_interface_parameter of mdio_i_temac : signal is "XIL_INTERFACENAME mdio_temac, CAN_DEBUG false";
  attribute x_interface_info of mdio_o_temac : signal is "xilinx.com:interface:mdio:1.0 mdio_temac MDIO_O";
  attribute x_interface_info of mdio_t_temac : signal is "xilinx.com:interface:mdio:1.0 mdio_temac MDIO_T";
  attribute x_interface_info of mdc_temac : signal is "xilinx.com:interface:mdio:1.0 mdio_temac MDC";
  attribute x_interface_info of GTX_CLK : signal is "xilinx.com:signal:clock:1.0 GTX_CLK CLK";
  attribute x_interface_mode of GTX_CLK : signal is "slave GTX_CLK";
  attribute x_interface_parameter of GTX_CLK : signal is "XIL_INTERFACENAME GTX_CLK, FREQ_HZ 125000000, FREQ_TOLERANCE_HZ 0, PHASE 0, CLK_DOMAIN system_processing_system7_0_0_FCLK_CLK1, INSERT_VIP 0";
  attribute x_core_info : string;
  attribute x_core_info of stub : architecture is "axi_ethernet_buffer_v2_0_26,Vivado 2025.2";
begin
end;
