# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fpga_pin.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_0_0/system_axi_ethernet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ethernet_0_0 || ORIG_REF_NAME==system_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_1_0/system_axi_ethernet_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ethernet_1_0 || ORIG_REF_NAME==system_axi_ethernet_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ethernet_1_dma_0/system_axi_ethernet_1_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ethernet_1_dma_0 || ORIG_REF_NAME==system_axi_ethernet_1_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_subset_converter_0_0 || ORIG_REF_NAME==system_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_uihdmitx_0_0/system_uihdmitx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uihdmitx_0_0 || ORIG_REF_NAME==system_uihdmitx_0_0} -quiet] -quiet

# IP: bd/system/ip/system_util_vector_logic_1_0/system_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_vector_logic_1_0 || ORIG_REF_NAME==system_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/system_mipi_csi2_rx_subsyst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mipi_csi2_rx_subsyst_0_0 || ORIG_REF_NAME==system_mipi_csi2_rx_subsyst_0_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ui_image_correction_0_0/system_ui_image_correction_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ui_image_correction_0_0 || ORIG_REF_NAME==system_ui_image_correction_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ui_demosaic_0_0/system_ui_demosaic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ui_demosaic_0_0 || ORIG_REF_NAME==system_ui_demosaic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_data128_96_0_0/system_data128_96_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_data128_96_0_0 || ORIG_REF_NAME==system_data128_96_0_0} -quiet] -quiet

# IP: bd/system/ip/system_data96_128_0_0/system_data96_128_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_data96_128_0_0 || ORIG_REF_NAME==system_data96_128_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ui_awb_1_3v_0_0/system_ui_awb_1_3v_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ui_awb_1_3v_0_0 || ORIG_REF_NAME==system_ui_awb_1_3v_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ui_image_cut_0_0/system_ui_image_cut_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ui_image_cut_0_0 || ORIG_REF_NAME==system_ui_image_cut_0_0} -quiet] -quiet

# IP: bd/system/ip/system_uifdma_dbuf_0_0/system_uifdma_dbuf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uifdma_dbuf_0_0 || ORIG_REF_NAME==system_uifdma_dbuf_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_uiFDMA_0_0/system_uiFDMA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uiFDMA_0_0 || ORIG_REF_NAME==system_uiFDMA_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_1_imp_xbar_0/system_axi_interconnect_1_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_1_imp_xbar_0 || ORIG_REF_NAME==system_axi_interconnect_1_imp_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_1_0/system_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_1_0 || ORIG_REF_NAME==system_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/system/ip/system_smartconnect_0_0/system_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_smartconnect_0_0 || ORIG_REF_NAME==system_smartconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_ui_imx415_0_0/system_ui_imx415_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ui_imx415_0_0 || ORIG_REF_NAME==system_ui_imx415_0_0} -quiet] -quiet

# IP: bd/system/ip/system_uidelay_0_0/system_uidelay_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uidelay_0_0 || ORIG_REF_NAME==system_uidelay_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_2_0/system_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_2_0 || ORIG_REF_NAME==system_xlconstant_2_0} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_1_0 || ORIG_REF_NAME==system_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_3_0/system_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_3_0 || ORIG_REF_NAME==system_xlconstant_3_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_1_imp_auto_pc_0/system_axi_interconnect_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_1_imp_auto_pc_0 || ORIG_REF_NAME==system_axi_interconnect_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_1_imp_auto_cc_0/system_axi_interconnect_1_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_interconnect_1_imp_auto_cc_0 || ORIG_REF_NAME==system_axi_interconnect_1_imp_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_4_0/system_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_4_0 || ORIG_REF_NAME==system_xlconstant_4_0} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/system_ooc.xdc
