# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "G:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.runs/synth_1/system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 7
set_param bd.open.in_stealth_mode 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.cache/wt [current_project]
set_property parent.project_path G:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj [current_project]
update_ip_catalog
set_property ip_output_repo g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib G:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/uisrc/rtl/system_wrapper.v
add_files G:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_4bad_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_4bad_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_0/bd_4bad_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_4bad_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_4bad_mac_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_4bad_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_4bad_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_2/bd_4bad_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/ip/ip_3/bd_4bad_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/bd_0/bd_4bad_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/system_axi_ethernet_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/synth/system_axi_ethernet_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_0_0/synth/system_axi_ethernet_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8bfc_eth_buf_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_0/synth/bd_8bfc_eth_buf_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8bfc_eth_buf_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_8bfc_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_8bfc_mac_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_8bfc_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_8bfc_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_2/bd_8bfc_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_3/bd_8bfc_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/bd_8bfc_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/system_axi_ethernet_1_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/synth/system_axi_ethernet_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/synth/system_axi_ethernet_1_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_dma_0/system_axi_ethernet_1_dma_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_dma_0/system_axi_ethernet_1_dma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_dma_0/system_axi_ethernet_1_dma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_22c6_phy_0.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_22c6_phy_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_22c6_phy_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_22c6_vfb_0_0_axisswitch_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_22c6_vfb_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_22c6_r_sync_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_3/bd_22c6_r_sync_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/bd_22c6_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/system_mipi_csi2_rx_subsyst_0_0_fixed_impl.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/system_mipi_csi2_rx_subsyst_0_0_fixed_impl.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/system_mipi_csi2_rx_subsyst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/system_mipi_csi2_rx_subsyst_0_0_fixed_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_zhenghe/blk_mem_gen_zhenghe_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_demosaic/blk_mem_gen_demosaic_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/ui_awb_1_3V.srcs/sources_1/ip/blk_mem_gen_awb_delay_signal/blk_mem_gen_awb_delay_signal_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_interconnect_1_imp_xbar_0/system_axi_interconnect_1_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_1/bd_919a_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_2/bd_919a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_3/bd_919a_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_4/bd_919a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_5/bd_919a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_6/bd_919a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_7/bd_919a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_8/bd_919a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_12/bd_919a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_13/bd_919a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_14/bd_919a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_18/bd_919a_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_19/bd_919a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_20/bd_919a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_21/bd_919a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_25/bd_919a_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_26/bd_919a_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_27/bd_919a_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_28/bd_919a_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_29/bd_919a_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_30/bd_919a_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_34/bd_919a_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_35/bd_919a_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_36/bd_919a_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_40/bd_919a_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_41/bd_919a_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_42/bd_919a_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_46/bd_919a_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_47/bd_919a_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_48/bd_919a_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_49/bd_919a_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_53/bd_919a_s06a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_54/bd_919a_sarn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_55/bd_919a_srn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_56/bd_919a_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_57/bd_919a_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_58/bd_919a_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_62/bd_919a_s07a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_63/bd_919a_sarn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_64/bd_919a_srn_5_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_65/bd_919a_sawn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_66/bd_919a_swn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_67/bd_919a_sbn_4_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_68/bd_919a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_69/bd_919a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_70/bd_919a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_71/bd_919a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_72/bd_919a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/bd_0/ip/ip_73/bd_919a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_interconnect_1_imp_auto_pc_0/system_axi_interconnect_1_imp_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_interconnect_1_imp_auto_cc_0/system_axi_interconnect_1_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_interconnect_1_imp_auto_cc_0/system_axi_interconnect_1_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_interconnect_1_imp_auto_cc_0/system_axi_interconnect_1_imp_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/constrs_1/new/fpga_pin.xdc
set_property used_in_implementation false [get_files G:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/constrs_1/new/fpga_pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_wrapper -part xc7z020clg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
