# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/system_ui_awb_1_3v_0_0.xci
# IP: The module: 'system_ui_awb_1_3v_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/ui_awb_1_3V.srcs/sources_1/ip/blk_mem_gen_awb_delay_signal/blk_mem_gen_awb_delay_signal.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_awb_delay_signal || ORIG_REF_NAME==blk_mem_gen_awb_delay_signal} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/ui_awb_1_3V.srcs/sources_1/ip/div_gen_awb/div_gen_awb.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_awb || ORIG_REF_NAME==div_gen_awb} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/ui_awb_1_3V.srcs/sources_1/ip/blk_mem_gen_awb_delay_signal/blk_mem_gen_awb_delay_signal_ooc.xdc

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/system_ui_awb_1_3v_0_0.xci
# IP: The module: 'system_ui_awb_1_3v_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/ui_awb_1_3V.srcs/sources_1/ip/blk_mem_gen_awb_delay_signal/blk_mem_gen_awb_delay_signal.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_awb_delay_signal || ORIG_REF_NAME==blk_mem_gen_awb_delay_signal} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/ui_awb_1_3V.srcs/sources_1/ip/div_gen_awb/div_gen_awb.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_awb || ORIG_REF_NAME==div_gen_awb} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_awb_1_3v_0_0/ui_awb_1_3V.srcs/sources_1/ip/blk_mem_gen_awb_delay_signal/blk_mem_gen_awb_delay_signal_ooc.xdc
