# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/blk_mem_gen_awb_delay_signal/blk_mem_gen_awb_delay_signal.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_awb_delay_signal || ORIG_REF_NAME==blk_mem_gen_awb_delay_signal} -quiet] -quiet

# IP: ip/div_gen_awb/div_gen_awb.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_awb || ORIG_REF_NAME==div_gen_awb} -quiet] -quiet

# XDC: i:/ISP_1x/ISP_4x/ui_awb_1_3V/ui_awb_1_3V.gen/sources_1/ip/blk_mem_gen_awb_delay_signal/blk_mem_gen_awb_delay_signal_ooc.xdc
