# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_axi_ethernet_1_0/system_axi_ethernet_1_0.xci
# IP: The module: 'system_axi_ethernet_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/bd_8bfc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc || ORIG_REF_NAME==bd_8bfc} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8bfc_eth_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_eth_buf_0 || ORIG_REF_NAME==bd_8bfc_eth_buf_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_1/bd_8bfc_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_mac_0 || ORIG_REF_NAME==bd_8bfc_mac_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_2/bd_8bfc_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_c_shift_ram_0_0 || ORIG_REF_NAME==bd_8bfc_c_shift_ram_0_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_3/bd_8bfc_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_c_counter_binary_0_0 || ORIG_REF_NAME==bd_8bfc_c_counter_binary_0_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_5/bd_8bfc_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_util_vector_logic_0_0 || ORIG_REF_NAME==bd_8bfc_util_vector_logic_0_0} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/bd_8bfc_ooc.xdc

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/system_axi_ethernet_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/synth/system_axi_ethernet_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/synth/system_axi_ethernet_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: G:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_axi_ethernet_1_0/system_axi_ethernet_1_0.xci
# IP: The module: 'system_axi_ethernet_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/bd_8bfc.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc || ORIG_REF_NAME==bd_8bfc} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_0/bd_8bfc_eth_buf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_eth_buf_0 || ORIG_REF_NAME==bd_8bfc_eth_buf_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_1/bd_8bfc_mac_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_mac_0 || ORIG_REF_NAME==bd_8bfc_mac_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_2/bd_8bfc_c_shift_ram_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_c_shift_ram_0_0 || ORIG_REF_NAME==bd_8bfc_c_shift_ram_0_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_3/bd_8bfc_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_c_counter_binary_0_0 || ORIG_REF_NAME==bd_8bfc_c_counter_binary_0_0} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_5/bd_8bfc_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_8bfc_util_vector_logic_0_0 || ORIG_REF_NAME==bd_8bfc_util_vector_logic_0_0} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/bd_8bfc_ooc.xdc

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/system_axi_ethernet_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/synth/system_axi_ethernet_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/synth/system_axi_ethernet_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_ethernet_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
