# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_3/bd_8bfc_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8bfc_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/06_ex_linux_QT_Drive_L2_7020/QT_Drive_Appendix/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_ethernet_1_0/bd_0/ip/ip_3/bd_8bfc_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_8bfc_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
