# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_22c6_vfb_0_0_axisswitch.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_vfb_0_0_axisswitch || ORIG_REF_NAME==bd_22c6_vfb_0_0_axisswitch} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_1/bd_22c6_vfb_0_0_sli.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_vfb_0_0_sli || ORIG_REF_NAME==bd_22c6_vfb_0_0_sli} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_2/bd_22c6_vfb_0_0_slo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_vfb_0_0_slo || ORIG_REF_NAME==bd_22c6_vfb_0_0_slo} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_22c6_vfb_0_0_axisswitch_ooc.xdc

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_22c6_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_22c6_vfb_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_22c6_vfb_0_0_axisswitch.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_vfb_0_0_axisswitch || ORIG_REF_NAME==bd_22c6_vfb_0_0_axisswitch} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_1/bd_22c6_vfb_0_0_sli.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_vfb_0_0_sli || ORIG_REF_NAME==bd_22c6_vfb_0_0_sli} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_2/bd_22c6_vfb_0_0_slo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_22c6_vfb_0_0_slo || ORIG_REF_NAME==bd_22c6_vfb_0_0_slo} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/ip_0/bd_22c6_vfb_0_0_axisswitch_ooc.xdc

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_2/bd_22c6_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_22c6_vfb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
