# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_ui_demosaic_0_0/system_ui_demosaic_0_0.xci
# IP: The module: 'system_ui_demosaic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_demosaic/blk_mem_gen_demosaic.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_demosaic || ORIG_REF_NAME==blk_mem_gen_demosaic} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_zhenghe/blk_mem_gen_zhenghe.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_zhenghe || ORIG_REF_NAME==blk_mem_gen_zhenghe} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_demosaic/blk_mem_gen_demosaic_ooc.xdc

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_zhenghe/blk_mem_gen_zhenghe_ooc.xdc

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_ui_demosaic_0_0/system_ui_demosaic_0_0.xci
# IP: The module: 'system_ui_demosaic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_demosaic/blk_mem_gen_demosaic.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_demosaic || ORIG_REF_NAME==blk_mem_gen_demosaic} -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_zhenghe/blk_mem_gen_zhenghe.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_zhenghe || ORIG_REF_NAME==blk_mem_gen_zhenghe} -quiet] -quiet

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_demosaic/blk_mem_gen_demosaic_ooc.xdc

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_ui_demosaic_0_0/ui_demosaic_4x_2_0.srcs/sources_1/ip/blk_mem_gen_zhenghe/blk_mem_gen_zhenghe_ooc.xdc
