# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_axi_interconnect_1_imp_xbar_0/system_axi_interconnect_1_imp_xbar_0.xci
# IP: The module: 'system_axi_interconnect_1_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_interconnect_1_imp_xbar_0/system_axi_interconnect_1_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_interconnect_1_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.srcs/sources_1/bd/system/ip/system_axi_interconnect_1_imp_xbar_0/system_axi_interconnect_1_imp_xbar_0.xci
# IP: The module: 'system_axi_interconnect_1_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/proj/fpga/zynq7020_mlk2/proj/linux_QT/QT/project/soc_prj/soc_prj.gen/sources_1/bd/system/ip/system_axi_interconnect_1_imp_xbar_0/system_axi_interconnect_1_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_interconnect_1_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
