# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/blk_mem_gen_demosaic/blk_mem_gen_demosaic.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_demosaic || ORIG_REF_NAME==blk_mem_gen_demosaic} -quiet] -quiet

# IP: ip/blk_mem_gen_zhenghe/blk_mem_gen_zhenghe.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_zhenghe || ORIG_REF_NAME==blk_mem_gen_zhenghe} -quiet] -quiet

# XDC: i:/ISP_1x/ISP_4x/ui_demosaic_4x_2_0/ui_demosaic_4x_2_0.gen/sources_1/ip/blk_mem_gen_demosaic/blk_mem_gen_demosaic_ooc.xdc

# XDC: i:/ISP_1x/ISP_4x/ui_demosaic_4x_2_0/ui_demosaic_4x_2_0.gen/sources_1/ip/blk_mem_gen_zhenghe/blk_mem_gen_zhenghe_ooc.xdc
